module.exports.authController = require("./auth.controller")
module.exports.userController = require("./user.controller")
module.exports.peopleController = require("./people.controller")
module.exports.complaintController = require("./complaint.controller")
module.exports.notificationController = require("./notification.controller")
